[package]
name = "bevy_libgdx_atlas"
version = "0.6.0"
edition = "2024"
authors = ["Rustunit <mail@rustunit.com>"]
description = "Support loading `libgdx.atlas` files (used for sprite sheets and such) as Bevy assets."
license = "MIT OR Apache-2.0"
repository = "https://github.com/rustunit/bevy_libgdx_atlas"
readme = "README.md"
keywords = ["bevy", "gamedev", "asset"]
categories = ["game-development"]

[lints]
workspace = true

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[dependencies]
bevy_camera = { version = "0.19", default-features = false }
bevy_asset = { version = "0.19", default-features = false }
bevy_ecs = { version = "0.19", default-features = false }
bevy_reflect = { version = "0.19", default-features = false }
bevy_image = { version = "0.19", default-features = false }
bevy_platform = { version = "0.19", default-features = false }
bevy_math = { version = "0.19", default-features = false }
bevy_app = { version = "0.19", default-features = false }
bevy_internal = { version = "0.19", features = ["bevy_image"] }
thiserror = "2.0"

[dev-dependencies]
pretty_assertions = "1"
bevy = "0.19"
